# The empty Grizzly extras configuration has nothing in it and should not.
# It is meant to override the default to add custom control parameters
# file in your own Grizzly customization package and setting GRIZZLY_CONFIG_EXTRAS
# to your customization file in the launch fil control.launch.
# Each parameter will need to be loaded in the correct namespace to
# be used. For example, for a Grizzly with a lower gear ratio.
# This can be used to change grizzly_velocity_controller/wheel_radius_multiplier
# to account for the change in the gearbox.
